### ISSUE TITLE
[1.21.1] Optional suggestion -thirdparty support

### ISSUE THREAD

**Issue by Cixon** [ItsFelix5/Stfu#1]
Firstly, I wanna thank you for this mod, super handy and light weight!
I have a suggestion, a little niche but bare with me:
![2024-08-30 22_42_28-Greenshot](https://github.com/user-attachments/assets/db3633b1-17e3-426c-98c1-0ab115126c44)

So, many mods including Better End does this annoying thing where they spam you with achievements upon world load or when joining a new server, I was wondering if there's anyway you could add an optional feature that'll hides it?

Source Code for Better End:
https://github.com/quiqueck/BetterEnd/blob/1.21/src/main/java/org/betterx/datagen/betterend/advancement/EndAdvancementDataProvider.java

**Comment by Cixon** [comment]
I made an attempt to make a datapack for the 'The Light at the End of the Game' achievement to hide it but I believe it's hardcoded...

This is pretty annoying because if you host a server the chat will get spammed and it just kinda feels like a watermark™

**Comment by Cixon** [comment]
> So unless I am wrong, (I am not very familliar with betterend) and this is actually obtrusive I might still do it but this is currently not planned.

gotcha, i mean, a option via config to hide all vanilla/modded achievement announcements via chat would suffice tbh. thanks for the reply!

**Comment by ItsFelix5** [comment]
A option via config to hide all achievement announcements will

**Comment by ItsFelix5** [comment]
Well if you state it like that... Sure!

**Comment by Cixon** [comment]
i humbly appreciate this, thank you!

**Comment by ItsFelix5** [comment]
I have implemented this but there is a bug with the translation keys so it will be released tomorrow with some other things

**Comment by Cixon** [comment]
![2024-09-25 20_49_06-Greenshot](https://github.com/user-attachments/assets/0731fd91-80b2-49cf-a045-c45170831dfa)

**Comment by Cixon** [comment]
chats aren't hidden in this update?

**Comment by ItsFelix5** [comment]
Did you disable them in chat settings

**Comment by ItsFelix5** [comment]
@Cixon is this fixed?

**Comment by Cixon** [comment]
> Did you disable them in chat settings?

I didn't know I had to disable it via chat, I figured your mod would have produced a config called stfu.json or something to disable achievement chat announcements. I prefer this method instead so that way all the changes are pre-loaded without interfering with the `options.txt` for my modpack.

**Comment by ItsFelix5** [comment]
I might fix this later but for now i recommend the your options shall be respected mod

**Comment by ItsFelix5** [comment]
@Cixon stfu now uses a dedicated config file

**Comment by ItsFelix5** [comment]
lmao

**Comment by Cixon** [comment]
> lmao

sorry, hi again. where is this config located or labeled as? i check my config folder but found nothing labeled as `stfu`. I even tried looking my world save `serverconfig `and got nothing.

**Comment by Cixon** [comment]
> it should generate at .config/stfu.txt once you change them

not sure why but it didn’t am I missing a dependency?

**Comment by ItsFelix5** [comment]
It does not use a dependency no, did you update the mod?

**Comment by Cixon** [comment]
> It does not use a dependency no, did you update the mod?

yeah i even tried to use a new pack setup. It’s this one, right?
https://modrinth.com/mod/shuttfup/version/1.2.1

**Comment by Cixon** [comment]
Try to download it and see, it’s possible u uploaded the wrong jar or just user error. I’m not sure but I tried to make a new profile on modrinth with only that .jar in it and nothing was generated.

**Comment by ItsFelix5** [comment]
Just tested it again and only thing that i noticed is that i accidentally put it in .config instead of config i will fix that in a minute

**Comment by ItsFelix5** [comment]
So it is `.config` on 1.2.1 and `config` on 1.2.2

**Comment by Cixon** [comment]
> So it is `.config` on 1.2.1 and `config` on 1.2.2

that explains it, although, i didn’t see a .config either…i’ll test later today. thanks again !
