### ISSUE TITLE
[INCOMPATIBILITY] (The Ceilands) World Fails to unlock on quit.

### ISSUE THREAD

**Issue by DurekuRyuu** [ItsFelix5/Stfu#10]
Type: Issue, Bug, Incompatibility (?)

**Describe the bug**
This mod causes my saved worlds to fail to open. Have no idea as to what the cause is aside from it only happening when this mod is enabled.
Identified this mod was the culprit not by seeing anything notable in the log or crash logs, but instead by a binary search.
Reduced a 400+ modlist down to what is attatched (34 active with 2 more candidates.) Seeing if I can attach the Prism modpack for good measure so you can test and evaluate it yourself.

**To Reproduce**
1. Boot attatched modpack  in Prism Launcher
https://drive.google.com/file/d/1iAG4QEt4Vr8ZPEKdHN2PC9M-fuyeaTsa/view?usp=sharing
2. Create world (I used Big Globe world type)
3. Save and quit
4. Re-open world
5. See error

**Expected behavior**
World should re-open as if it is not locked, worlds should be unlocked when they are successfully 'save and quit' out of.

 Minecraft Version: 1.20.1

**Additional context**
Game log
[DP 0.1.0 BS5 latest.log](https://github.com/user-attachments/files/17963612/DP.0.1.0.BS5.latest.log)

I am on the latest version, 1.2.3 for 1.20.1

**Comment by DurekuRyuu** [comment]
Still happens with STFU enabled and not Ceilands, but granted, that was with the full modlist, so its likely something else.
Thanks for taking a look at this.

**Comment by ItsFelix5** [comment]
With the testing I have done it works with only the ceilands and stfu but maybe there are multiple incompatibilities?
