### ISSUE TITLE
[Visual issue] Legendary Tooltips

### ISSUE THREAD

**Issue by ElenaNya** [ItsFelix5/Stfu#11]
**Describe the bug**
Vissual issue.

**Steps to reproduce the behavior:**
Simply install mods listed in the additional context.

**Expected behavior**
Beautiful outlines on the tooltips from the Legendary Tooltips mod.

**Screenshots**
![image](https://github.com/user-attachments/assets/54c725bc-58cf-4b39-9f70-ce04f81da600)

**Minecraft Version:**
1.21.1
NeoForge 21.1.83

**Additional context**
Stfu-1.2.3
LegendaryTooltips-1.21-neoforge-1.4.11
Prism-1.21-neoforge-1.0.9
Iceberg-1.21.1-neoforge
connector-2.0.0-beta.4+1.21.1-full
ConnectorExtras-1.12.1+1.21.1

**Comment by ItsFelix5** [comment]
Fixed in 1.3.1

**Comment by ItsFelix5** [comment]
I will backport this fix later to 1.21.1

**Comment by ItsFelix5** [comment]
There you go!

**Comment by ElenaNya** [comment]
> There you go!

Thank you! Now, for some reason, it keeps crashing. I'll try to figure out which mod is causing the issue 

[latest.log](https://github.com/user-attachments/files/18125908/latest.log)

[crash-2024-12-13_13.48.26-client.txt](https://github.com/user-attachments/files/18125906/crash-2024-12-13_13.48.26-client.txt)

**Comment by ItsFelix5** [comment]
Is this only with stfu, it seems like it is vivecraft or iris causing this issue.

**Comment by ElenaNya** [comment]
> Is this only with stfu, it seems like it is vivecraft, vrapi or iris causing this issue.

removed Vivecraft and Iris, but the error still persists. I'll try to figure out which of the 250+ mods is causing the incompatibility, but I'll also keep you updated.

[crash-2024-12-13_13.56.04-client.txt](https://github.com/user-attachments/files/18126011/crash-2024-12-13_13.56.04-client.txt)

[latest.log](https://github.com/user-attachments/files/18126012/latest.log)

**Comment by ElenaNya** [comment]
Oh, I just can't launch Minecraft at all with this mods

![image](https://github.com/user-attachments/assets/a62494e5-96f0-4957-93b4-a5c36fda89a6)

**Comment by ItsFelix5** [comment]
It seems to be an connector bug then?

**Comment by ElenaNya** [comment]
> It seems to be an connector bug then? Also connectorextras/ffapi is not nessicary for it to crash.

Yeah I think. Thanks for the help! I'm not very experienced with this, so unfortunately, can't quickly figure out which mod is causing the incompatibility. Just to note, stfu-1.2.3 launches without any issues

![image](https://github.com/user-attachments/assets/13861f4c-9411-48d3-83ba-28e83d59420d)

**Comment by ItsFelix5** [comment]
I have narrowed this issue down to the mount hud, i will be opening an issue on connectors repo.
For now here is a jar with that disabled (github does not like jars apparently so it is a zip, just rename it to a jar)
[Stfu-1.3.1.zip](https://github.com/user-attachments/files/18126165/Stfu-1.3.1.zip)
