### ISSUE TITLE
[BUG] crash on startup

### ISSUE THREAD

**Issue by mateus3c** [ItsFelix5/Stfu#13]
minecraft version 1.21.1, Stfu-1.3.1

`Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector alwaysRenderFood(Lnet/minecraft/class_329;Lnet/minecraft/class_1309;)I in stfu.mixins.json:BetterHud from mod stfu failed injection check, (0/1) succeeded. Scanned 0 target(s). Using refmap Stfu-refmap.json`

Crash Report
[mclo.gs/PrnzqTL](https://mclo.gs/PrnzqTL)

latest.log
[mclo.gs/6IgNB7f](https://mclo.gs/6IgNB7f)

**Comment by ItsFelix5** [comment]
Stfu is not compatible with bettermountHUD as it replaces that, i think removing that should fix your issue.
