### ISSUE TITLE
Underated

### ISSUE THREAD

**Issue by pierrelasse** [ItsFelix5/Stfu#2]
Only 482 downloads!?
You should also enable discussions so I don't have to make a issue for this lol

**Comment by ItsFelix5** [comment]
Ok!

**Comment by pierrelasse** [comment]
When I found this mod on like page 50, I had 3 mods I could replace with this one. Great work.
What do you mean with bumping it?

**Comment by ItsFelix5** [comment]
Getting it of page 50
