### ISSUE TITLE
[1.2.2] Stfu x Legacy 4J bug -GUI tooltip box broken

### ISSUE THREAD

**Issue by Cixon** [ItsFelix5/Stfu#6]
### Type
Visual issue. Mod incompatibility.

### Describe the bug
Strange behavior, this bug does not exist for [v1.0](https://modrinth.com/mod/shuttfup/version/1.0) STFU.

![2024-10-02 19_42_33-Greenshot](https://github.com/user-attachments/assets/31a1ffbc-bb07-42d0-aaf5-8548e3b4cb59)

![2024-10-02 19_44_43-Greenshot](https://github.com/user-attachments/assets/df8dae72-d376-4808-9ce4-a4fa4c539c1e)

**To Reproduce**
1. Install 1.2.2 STFU
2. Install latest 1.7.4 L4J **WITH fabric API**
3. Load launcher
4. See issue

**Expected behavior**
The text is suppose to perfectly fit in the boxes, you can see this work properly if you disable STFU or downgrade to v1.0.

 Minecraft Version: 
1.21.1

**Additional context**
This bug occurs for both fabric and neoforge version of L4J.

Source code area you may be looking for? I could be wrong, do not rely on me:
https://github.com/Wilyicaro/Legacy-Minecraft/tree/1.21/common/src/main/java/wily/legacy/client/screen

**Comment by ItsFelix5** [comment]
This probably an issue with the tooltip fix il take a look at this later

**Comment by ItsFelix5** [comment]
Just added a simple `disabled = FabricLoader.getInstance().isModLoaded("legacy")` so it should be fixed now

**Comment by Cixon** [comment]
> Just added a simple `disabled = FabricLoader.getInstance().isModLoaded("legacy")` so it should be fixed now

i’ll check it out when i get home, thanks again!
