### ISSUE TITLE
[SUGGESTION] 1.20.1 Backport?

### ISSUE THREAD

**Issue by Fyoncle** [ItsFelix5/Stfu#7]
**Please describe your request.**
Can we get a backport? :D

**Comment by ItsFelix5** [comment]
yes

**Comment by Fyoncle** [comment]
> yes

Woohoooo :)

**Comment by ItsFelix5** [comment]
Stfu is now available for 1.20 and 1.20.1!

**Comment by Fyoncle** [comment]
> Stfu is now available for 1.20 and 1.20.1!

Since the mod called stfu, i feel insulted wherever i hear that lmao.

Anyways thank you so much ❤️
