### ISSUE TITLE
[CRASH] 1.20.1 Compiled With Wrong Java Version

### ISSUE THREAD

**Issue by Fyoncle** [ItsFelix5/Stfu#9]
Type: [Crash]

**Describe the bug**

**To Reproduce**
1. Install Stfu 1.20.1
2. Open the game

**Expected behavior**
For the game to launch without any problems.

 Minecraft Version: 1.20.1

**Logs**
https://mclo.gs/xL873pK

**Comment by ItsFelix5** [comment]
I thought i fixed that :(

**Comment by Fyoncle** [comment]
> I thought i fixed that :(

lol :D

**Comment by ItsFelix5** [comment]
Classic gradle misconfiguration, everything should be fixed now!
